// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAspNetProject.InfraStructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyAspNetProject.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyAspNetProject.Models.Domain.KlassEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("group");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasMaxLength(2)
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_klass");

                    b.HasIndex("Year")
                        .HasDatabaseName("ix_klass_year");

                    b.ToTable("klass", (string)null);
                });

            modelBuilder.Entity("MyAspNetProject.Models.Domain.SubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subject");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subject_name");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("MyAspNetProject.Models.Domain.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("image_url");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_entity_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_user_entity_phone_number");

                    b.ToTable("user_entity", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SubjectEntityTeacherEntity", b =>
                {
                    b.Property<Guid>("SubjectEntitiesId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_entities_id");

                    b.Property<Guid>("TeachersId")
                        .HasColumnType("uuid")
                        .HasColumnName("teachers_id");

                    b.HasKey("SubjectEntitiesId", "TeachersId")
                        .HasName("pk_subject_teacher");

                    b.HasIndex("TeachersId")
                        .HasDatabaseName("ix_subject_teacher_teachers_id");

                    b.ToTable("subject_teacher", (string)null);
                });

            modelBuilder.Entity("MyAspNetProject.Models.Domain.StudentEntity", b =>
                {
                    b.HasBaseType("MyAspNetProject.Models.Domain.UserEntity");

                    b.Property<Guid>("KlassId")
                        .HasColumnType("uuid")
                        .HasColumnName("klass_id");

                    b.Property<int?>("Performance")
                        .HasColumnType("integer")
                        .HasColumnName("performance");

                    b.HasIndex("KlassId")
                        .HasDatabaseName("ix_student_klass_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("MyAspNetProject.Models.Domain.TeacherEntity", b =>
                {
                    b.HasBaseType("MyAspNetProject.Models.Domain.UserEntity");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<Guid?>("HeadClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_class_id");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric")
                        .HasColumnName("salary");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("SubjectEntityTeacherEntity", b =>
                {
                    b.HasOne("MyAspNetProject.Models.Domain.SubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("SubjectEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_teacher_subject_subject_entities_id");

                    b.HasOne("MyAspNetProject.Models.Domain.TeacherEntity", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_teacher_teacher_teachers_id");
                });

            modelBuilder.Entity("MyAspNetProject.Models.Domain.StudentEntity", b =>
                {
                    b.HasOne("MyAspNetProject.Models.Domain.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("MyAspNetProject.Models.Domain.StudentEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_user_entity_id");

                    b.HasOne("MyAspNetProject.Models.Domain.KlassEntity", "KlassEntity")
                        .WithMany("Students")
                        .HasForeignKey("KlassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_klasses_klass_id");

                    b.Navigation("KlassEntity");
                });

            modelBuilder.Entity("MyAspNetProject.Models.Domain.TeacherEntity", b =>
                {
                    b.HasOne("MyAspNetProject.Models.Domain.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("MyAspNetProject.Models.Domain.TeacherEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_user_entity_id");
                });

            modelBuilder.Entity("MyAspNetProject.Models.Domain.KlassEntity", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
